### ISSUE TITLE
update example

### ISSUE THREAD

**Issue by macguffin** [NoProtocol/gsap-pixi-plugin#2]
Hi thanks for this, great little plugin, makes it much easier to tween multiple properties when one of them is scale.
Not an issue just a suggestion, might be worth showing onComplete or something similar in your example so people don't put it inside the pixi:{}. 
e.g.
TweenLite.set(sprite, { pixi: {
    alpha: 0.85,
    anchor: 0.5,
    scaleX: 0.7
},onComplete:foo});

Cheers and thanks again
Matt

**Comment by karthickvkumar** [comment]
+1

**Comment by macguffin** [comment]
FYI there is now an official GSAP pixi plugin, you might want to try that.
